### ISSUE TITLE
Machine and Multiblock checklist

### ISSUE THREAD

**Issue by liach** [Railcraft/Railcraft#1373]
Here are the machines and multiblocks to be ported.

- [x] Blast Furnace 
- [x] Coke Oven
- [x] ~Engines~ (@Generalcamo is doing a redesign of them - Moved to #1388 because it will be mj-only)
- [x] ~Engraving Bench (private code)~ <- moved to #890
- [x] Flux Transformer
- [x] Force Track Emitter (needs to fix functionality)
- [x] Iron Tank
- [x] Rock Crusher
- [x] Steam Boiler (#1484, thanks TheCodedOne)
- [x] Steam Oven
- [x] Turbine (Renamed to Steam Turbine)
- [x] Water Tank (#1389)
- [x] Metal Chest (rendering)
- [x] Void chest (rendering)
- [x] Admin steam producer

:white_circle: : work in progress

~They **MUST** be completed before the mod is ported to 1.12.2.~
They'd be completed before 1.12.2 release at best.
According to the wiki:
>Device:Blast Furnace | factory, device
Device:Cart Dispenser | automation, device
Device:Coke Oven | device, factory
Device:Detectors | automation, cart, device, train, outdated
Device:Electric Shunting Wire | device, electric
Device:Engines | energy, steam, device
Device:Engraving Bench | emblem, device
Device:Feed Station | automation, device, farm
Device:Flux Transformer | device, electric
Device:Force Track Emitter | device, electric, track
Device:Iron Tank | device, fluid, transport
Device:Item Loaders | automation, device
Device:Liquid Loaders | device, fluid, transport
Device:Rock Crusher | factory, device
Device:Steam Boiler | device, energy, steam
Device:Steam Oven | steam, device, factory
Device:Steam Turbine | ic2, energy, steam, device, electric
Device:Switch Lever | switching, device
Device:Switch Motor | controller, device, signal, switching
Device:Water Tank | device, fluid, transport
Device:World Anchor | chunkloading, device

That's all.

**Comment by liach** [comment]
@Dockter FYI, I think we may move to 1.12 once all of these except engraving bench is ported.

**Comment by liach** [comment]
Chests ported in 2849d9064b9fb990b73a4a9719185df7401eec23

**Comment by border999** [comment]
building was finally successful?

**Comment by liach** [comment]
yep, seems just 4 more

**Comment by liach** [comment]
I am working on turbine now. Because of #1481, I am renaming the old turbine to steam_turbine.

**Comment by liach** [comment]
Closing as the current goals are done.

**Comment by border999** [comment]
A truly awesome thing to hear
